sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # Decrypts the file containing our gcloud key
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-acount.json
    - gcloud config set project multi-k8s-287017
    - gcloud congig set compute/zone us-east1-b
    - gcloud container clusters get-credentials multi-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t gabrielgelgor/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gabrielgelgor/react-test npm run test

deploy:
    provider: script # Let travis know to use a custom deployment script
    script: bash ./deploy.sh # How to fire up the deploy script
    on:
        branch: master